### PR TITLE
Development

### PR DESCRIPTION
**Pull request by nahukas**

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work team :clap: . However, some requirements needs to be implemented in order for us to approve your project. check below :arrow_down: 

#### Page structure

##### Navigation bar

* [x] It has a link with text on the leftmost side.
> You are using a span element not a link :mag: 
* [x] The NY Times logo is a link.


#### Implementation details

##### Navigation bar

##### Footer

* [ ] It should have a fixed position (it sticks to the bottom part of the screen).
- **[REQUIRED]** you should have a fixed footer that sits at the bottom of the viewport.
- Check the original page for inspiration. :stars: 

#### General requirements:

- Add a more info to your readme (e.g. project's description, assignment link, technologies used, link to gitub profile, etc..)

- You project is missing linter configuration. Follow microverse [guide](https://github.com/microverseinc/linters-config/tree/master/css) to set it up.

### That's it :relaxed: . When finished, kindly resubmit another code review form :pray:

**Comment by nahukas** [comment]
> ### Great work team 👏 . However, some requirements needs to be implemented in order for us to approve your project. check below ⬇️
> #### Page structure
> ##### Navigation bar
> * [x]  It has a link with text on the leftmost side.
> 
> > You are using a span element not a link 🔍
> 
> * [x]  The NY Times logo is a link.
> 
> #### Implementation details
> ##### Navigation bar
> ##### Footer
> * [ ]  It should have a fixed position (it sticks to the bottom part of the screen).
> 
> * **[REQUIRED]** you should have a fixed footer that sits at the bottom of the viewport.
> * Check the original page for inspiration. 🌠
> 
> #### General requirements:
> * Add a more info to your readme (e.g. project's description, assignment link, technologies used, link to gitub profile, etc..)
> * You project is missing linter configuration. Follow microverse [guide](https://github.com/microverseinc/linters-config/tree/master/css) to set it up.
> 
> ### That's it ☺️ . When finished, kindly resubmit another code review form 🙏

Hi Ahmed,
Are you sure that the footer has a fixed position? Because I am right now at nytimes.com and my footer is not fixed at all. Are you talking about the promotion footer that appears when you are not logged in?

Thanks.
Luis and Nahuel

**Comment by stratospherique** [comment]
yes Team, I meant the promotion footer :relieved:

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great effort implementing the suggested changes :clap: . Yet, you still haven't implemented two of them. check below :arrow_down: 

- The fixed footer, You can try to copy the bottom banner of the original page
image

- You project is missing linter configuration. Follow microverse [guide](https://github.com/microverseinc/linters-config/tree/master/css) to set it up.

### That's it :relaxed: . When finished, kindly resubmit another code review form :pray:

**Comment by luis-novoa** [comment]
Hi Ahmed! We forgot to turn on the linter on this repository, but now it's working. Stickler keeps returning an error saying "job errored out when processing", and we don't know what that means. Google isn't helping either. Do you know what is this about?

**Review by bolah2009 — CHANGES_REQUESTED** [review]
# Awesome job team :clap: 

### [The clone](https://raw.githack.com/nahukas/new-york-times/0b9a1b7269c93755d8da779c2ac018252c4d82d1/index.html) looks good to me, uses CSS positioning effectively. :100: 

Please fix linter errors and [HTML validations error/warning](https://validator.w3.org/nu/?doc=https%3A%2F%2Fraw.githack.com%2Fnahukas%2Fnew-york-times%2F0b9a1b7269c93755d8da779c2ac018252c4d82d1%2Findex.html) and submit another code review request.

Check linter warnings locally on your machine:

> 
> 4. Stickler does not work and nothing helps 💥 - run [stylelint](https://stylelint.io/) in your local env:
>     - run `npm install stylelint stylelint-config-recommended --save-dev`  (not sure how to use npm? Read [this](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm))
>     - run `npx stylelint .` (or more precisely `npx stylelint style.css`)
>     - fix linter errors

Learn more [here](https://github.com/microverseinc/linters-config/tree/master/css#troubleshooting)

#### :recycle: Changes required

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

**Review by whiz25 — APPROVED** [review]
## Awesome :clap: @nahukas 
You have met all the requirements for this project. I wish you success in the next projects.

**Pull request merged**
